import { Language } from './types';

// Default backend URL for local development. Replace with your actual backend URL for production.
export const API_BASE_URL = 'https://anandvelpuri-team-bahubali-backend.hf.space';
// Read the OpenWeather API key from Vite environment variables.
// NOTE: This still exposes the key to client-side bundles. For full security,
// proxy requests through your backend and keep the key server-side.
export const WEATHER_API_KEY = import.meta.env.VITE_OPEN_WEATHER_API_KEY as string | undefined;

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    title: 'AgroLens',
    language: 'Language',
    cropDiseaseDetection: 'Crop Disease Detection',
    uploadPrompt: 'Click or drag to upload a crop image',
    uploadFromFile: 'Upload from File',
    useCamera: 'Use Camera',
    capture: 'Capture',
    cancel: 'Cancel',
    uploading: 'Uploading...',
    detect: 'Detect Disease',
    analyzing: 'Analyzing Image...',
    weatherForecast: 'Weather Forecast',
    today: 'Today',
    tomorrow: 'Tomorrow',
    error: 'An error occurred. Please try again.',
    errorApiConnection: 'Connection Error: Could not connect to the server at {url}. Please ensure the backend is running and allows requests from this page (CORS).',
    agroChat: 'AgroChat',
    chatPlaceholder: 'Ask anything about this diagnosis...',
    chatError: 'Sorry, I couldn\'t respond. Please try again.',
    noCropDetected: 'No crop detected',
    healthyCrop: 'Healthy Crop',
    retranslating: 'Updating language...',
    detectAnother: 'Detect Another',
    summary: 'Summary',
    causes: 'Possible Causes',
    medicines: 'Suggested Medicines',
    precautions: 'Precautions',
    disclaimer: 'Disclaimer',
    dosage: 'Dosage/Application',
    notes: 'Notes',
    chatGreeting: 'I see your crop might have "{diseaseName}". How can I help you with this?',
    errorNoCamera: 'No camera found. Please connect a camera and try again.',
    errorCameraPermission: 'Camera access was denied. Please allow camera permission in your browser settings.',
    errorCameraGeneric: 'Could not access camera. Please try again.',
    weatherLoading: 'Loading weather...',
    weatherErrorLocation: 'Could not get your location. Please allow location access to see the weather.',
    weatherErrorPermissionDenied: 'Location access was denied. Please enable it in your browser settings to see the weather.',
    weatherErrorPositionUnavailable: 'Your location could not be determined at this time. Please try again.',
    weatherErrorTimeout: 'Request for location timed out. Please try again.',
    weatherErrorApi: 'Could not fetch weather data. Please try again later.',
    weatherErrorNoKey: 'Weather service is not configured. Please add your OpenWeather API key.',
    noValidLeafDetected: 'No valid plant leaf detected. Please upload a clear image of a plant leaf.',
    tryAgain: 'Try again',
    tryAnother: 'Try another',
  },
  te: {
    title: 'అగ్రోలెన్స్',
    language: 'భాష',
    cropDiseaseDetection: 'పంట వ్యాధి నిర్ధారణ',
    uploadPrompt: 'పంట చిత్రాన్ని అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి లేదా లాగండి',
    uploadFromFile: 'ఫైల్ నుండి అప్‌లోడ్ చేయండి',
    useCamera: 'కెమెరాను ఉపయోగించండి',
    capture: 'క్యాప్చర్',
    cancel: 'రద్దు చేయి',
    uploading: 'అప్‌లోడ్ అవుతోంది...',
    detect: 'వ్యాధిని గుర్తించండి',
    analyzing: 'చిత్రాన్ని విశ్లేషిస్తోంది...',
    weatherForecast: 'వాతావరణ సూచన',
    today: 'ఈ రోజు',
    tomorrow: 'రేపు',
    error: 'లోపం సంభవించింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    errorApi: 'సర్వర్ నుండి ప్రతిస్పందన పొందడం సాధ్యం కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    errorApiConnection: 'కనెక్షన్ లోపం: {url} వద్ద సర్వర్‌కు కనెక్ట్ కాలేదు. దయచేసి బ్యాకెండ్ రన్ అవుతోందని మరియు ఈ పేజీ నుండి అభ్యర్థనలను అనుమతిస్తుందని నిర్ధారించుకోండి (CORS).',
    agroChat: 'అగ్రోచాట్',
    chatPlaceholder: 'ఈ నిర్ధారణ గురించి ఏదైనా అడగండి...',
    chatError: 'క్షమించండి, నేను స్పందించలేకపోయాను. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    noCropDetected: 'పంట కనుగొనబడలేదు',
    healthyCrop: 'ఆరోగ్యకరమైన పంట',
    retranslating: 'భాష నవీకరించబడుతోంది...',
    detectAnother: 'మరొకటి గుర్తించండి',
    summary: 'సారాంశం',
    causes: 'సాధ్యమయ్యే కారణాలు',
    medicines: 'సూచించిన మందులు',
    precautions: 'జాగ్రత్తలు',
    disclaimer: 'నిరాకరణ',
    dosage: 'మోతాదు/అప్లికేషన్',
    notes: 'గమనికలు',
    chatGreeting: 'మీ పంటకు "{diseaseName}" సోకినట్లు నేను గమనించాను. దీనికి సంబంధించి నేను మీకు ఎలా సహాయపడగలను?',
    errorNoCamera: 'కెమెరా కనుగొనబడలేదు. దయచేసి కెమెరాను కనెక్ట్ చేసి మళ్ళీ ప్రయత్నించండి.',
    errorCameraPermission: 'కెమెరా యాక్సెస్ నిరాకరించబడింది. దయచేసి మీ బ్రౌజర్ సెట్టింగ్‌లలో కెమెరా అనుమతిని అనుమతించండి.',
    errorCameraGeneric: 'కెమెరాను యాక్సెస్ చేయడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    weatherLoading: 'వాతావరణం లోడ్ అవుతోంది...',
    weatherErrorLocation: 'మీ స్థానాన్ని పొందడం సాధ్యం కాలేదు. వాతావరణాన్ని చూడటానికి దయచేసి స్థాన ప్రాప్యతను అనుమతించండి.',
    weatherErrorPermissionDenied: 'స్థాన ప్రాప్యత నిరాకరించబడింది. వాతావరణాన్ని చూడటానికి దయచేసి మీ బ్రౌజర్ సెట్టింగ్‌లలో దీన్ని ప్రారంభించండి.',
    weatherErrorPositionUnavailable: 'ప్రస్తుతం మీ స్థానాన్ని గుర్తించడం సాధ్యం కాలేదు. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    weatherErrorTimeout: 'స్థానం కోసం అభ్యర్థన సమయం ముగిసింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    weatherErrorApi: 'వాతావరణ డేటాను పొందడం సాధ్యం కాలేదు. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి.',
    weatherErrorNoKey: 'వాతావరణ సేవ కాన్ఫిగర్ చేయబడలేదు. దయచేసి మీ OpenWeather API కీని జోడించండి.',
    noValidLeafDetected: 'సరైన మొక్క ఆకును గుర్తించలేకపోయాం. దయచేసి మొక్క ఆకును స్పష్టంగా అప్‌లోడ్ చేయండి.',
    tryAgain: 'మళ్లీ ప్రయత్నించండి',
    tryAnother: 'ఇంకొకదాన్ని ప్రయత్నించండి',
  },
  hi: {
    title: 'एग्रोलेंस',
    language: 'भाषा',
    cropDiseaseDetection: 'फसल रोग का पता लगाना',
    uploadPrompt: 'फसल की छवि अपलोड करने के लिए क्लिक करें या खींचें',
    uploadFromFile: 'फ़ाइल से अपलोड करें',
    useCamera: 'कैमरे का उपयोग करें',
    capture: 'कैप्चर',
    cancel: 'रद्द करना',
    uploading: 'अपलोड हो रहा है...',
    detect: 'रोग का पता लगाएं',
    analyzing: 'छवि का विश्लेषण हो रहा है...',
    weatherForecast: 'मौसम पूर्वानुमान',
    today: 'आज',
    tomorrow: 'कल',
    error: 'एक त्रुटि हुई। कृपया पुन: प्रयास करें।',
    errorApi: 'सर्वर से प्रतिक्रिया नहीं मिल सकी। कृपया पुन: प्रयास करें।',
    errorApiConnection: 'कनेक्शन त्रुटि: {url} पर सर्वर से कनेक्ट नहीं हो सका। कृपया सुनिश्चित करें कि बैकएंड चल रहा है और इस पृष्ठ से अनुरोधों की अनुमति देता है (CORS)।',
    agroChat: 'एग्रोचैट',
    chatPlaceholder: 'इस निदान के बारे में कुछ भी पूछें...',
    chatError: 'क्षमा करें, मैं जवाब नहीं दे सका। कृपया पुन: प्रयास करें।',
    noCropDetected: 'कोई फसल नहीं मिली',
    healthyCrop: 'स्वस्थ फसल',
    retranslating: 'भाषा अपडेट हो रही है...',
    detectAnother: 'दूसरा पता लगाएँ',
    summary: 'सारांश',
    causes: 'संभावित कारण',
    medicines: 'सुझाई गई दवाएं',
    precautions: 'सावधानियां',
    disclaimer: 'अस्वीकरण',
    dosage: 'खुराक/आवेदन',
    notes: 'टिप्पणियाँ',
    chatGreeting: 'मुझे लगता है कि आपकी फसल में "{diseaseName}" हो सकता है। मैं इस बारे में आपकी कैसे मदद कर सकता हूँ?',
    errorNoCamera: 'कोई कैमरा नहीं मिला। कृपया एक कैमरा कनेक्ट करें और पुनः प्रयास करें।',
    errorCameraPermission: 'कैमरा एक्सेस से वंचित कर दिया गया था। कृपया अपनी ब्राउज़र सेटिंग्स में कैमरा अनुमति दें।',
    errorCameraGeneric: 'कैमरे तक नहीं पहुंच सका। कृपया पुन: प्रयास करें।',
    weatherLoading: 'मौसम लोड हो रहा है...',
    weatherErrorLocation: 'आपका स्थान प्राप्त नहीं हो सका। मौसम देखने के लिए कृपया स्थान पहुंच की अनुमति दें।',
    weatherErrorPermissionDenied: 'स्थान पहुंच से इनकार कर दिया गया था। मौसम देखने के लिए कृपया इसे अपनी ब्राउज़र सेटिंग्स में सक्षम करें।',
    weatherErrorPositionUnavailable: 'इस समय आपका स्थान निर्धारित नहीं किया जा सका। कृपया पुन: प्रयास करें।',
    weatherErrorTimeout: 'स्थान के लिए अनुरोध का समय समाप्त हो गया। कृपया पुनः प्रयास करें।',
    weatherErrorApi: 'मौसम डेटा प्राप्त नहीं हो सका। कृपया बाद में पुन: प्रयास करें।',
    weatherErrorNoKey: 'मौसम सेवा कॉन्फ़िगर नहीं है। कृपया अपनी OpenWeather API कुंजी जोड़ें।',
    noValidLeafDetected: 'कोई मान्य पौधे की पत्ती नहीं मिली। कृपया पत्ते की एक स्पष्ट छवि अपलोड करें।',
    tryAgain: 'फिर से कोशिश करें',
    tryAnother: 'दूसरा कोशिश करें',
  },
  es: {
    title: 'AgroLens',
    language: 'Idioma',
    cropDiseaseDetection: 'Detección de Enfermedades de Cultivos',
    uploadPrompt: 'Haga clic o arrastre para cargar una imagen del cultivo',
    uploadFromFile: 'Subir desde archivo',
    useCamera: 'Usar cámara',
    capture: 'Capturar',
    cancel: 'Cancelar',
    uploading: 'Subiendo...',
    detect: 'Detectar Enfermedad',
    analyzing: 'Analizando imagen...',
    weatherForecast: 'Pronóstico del Tiempo',
    today: 'Hoy',
    tomorrow: 'Mañana',
    error: 'Ocurrió un error. Por favor, inténtelo de nuevo.',
    errorApi: 'No se pudo obtener una respuesta del servidor. Por favor, inténtelo de nuevo.',
    errorApiConnection: 'Error de conexión: No se pudo conectar con el servidor en {url}. Asegúrese de que el backend se esté ejecutando y permita solicitudes desde esta página (CORS).',
    agroChat: 'AgroChat',
    chatPlaceholder: 'Pregunte cualquier cosa sobre este diagnóstico...',
    chatError: 'Lo siento, no pude responder. Por favor, inténtelo de nuevo.',
    noCropDetected: 'No se detectó ningún cultivo',
    healthyCrop: 'Cultivo Sano',
    retranslating: 'Actualizando idioma...',
    detectAnother: 'Detectar Otro',
    summary: 'Resumen',
    causes: 'Posibles Causas',
    medicines: 'Medicamentos Sugeridos',
    precautions: 'Precauciones',
    disclaimer: 'Descargo de responsabilidad',
    dosage: 'Dosis/Aplicación',
    notes: 'Notas',
    chatGreeting: 'Veo que su cultivo podría tener "{diseaseName}". ¿Cómo puedo ayudarle con esto?',
    errorNoCamera: 'No se encontró ninguna cámara. Conecte una cámara y vuelva a intentarlo.',
    errorCameraPermission: 'Se denegó el acceso a la cámara. Permita el permiso de la cámara en la configuración de su navegador.',
    errorCameraGeneric: 'No se pudo acceder a la cámara. Por favor, inténtelo de nuevo.',
    weatherLoading: 'Cargando el tiempo...',
    weatherErrorLocation: 'No se pudo obtener su ubicación. Por favor, permita el acceso a la ubicación para ver el tiempo.',
    weatherErrorPermissionDenied: 'Se denegó el acceso a la ubicación. Habilítelo en la configuración de su navegador para ver el tiempo.',
    weatherErrorPositionUnavailable: 'No se pudo determinar su ubicación en este momento. Por favor, inténtelo de nuevo.',
    weatherErrorTimeout: 'La solicitud de ubicación ha caducado. Por favor, inténtelo de nuevo.',
    weatherErrorApi: 'No se pudieron obtener los datos meteorológicos. Por favor, inténtelo de nuevo más tarde.',
    weatherErrorNoKey: 'El servicio meteorológico no está configurado. Por favor, agregue su clave de API de OpenWeather.',
    noValidLeafDetected: 'No se detectó una hoja de planta válida. Por favor, cargue una imagen clara de una hoja de planta.',
    tryAgain: 'Intentar de nuevo',
    tryAnother: 'Intentar otro',
  },
  ta: {
    title: 'அக்ரோலென்ஸ்',
    language: 'மொழி',
    cropDiseaseDetection: 'பயிர் நோய் கண்டறிதல்',
    uploadPrompt: 'பயிர் படத்தை பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுக்கவும்',
    uploadFromFile: 'கோப்பிலிருந்து பதிவேற்றவும்',
    useCamera: 'கேமராவைப் பயன்படுத்தவும்',
    capture: 'படம் எடு',
    cancel: 'ரத்து செய்',
    uploading: 'பதிவேற்றுகிறது...',
    detect: 'நோயைக் கண்டறியவும்',
    analyzing: 'படத்தை பகுப்பாய்வு செய்கிறது...',
    weatherForecast: 'வானிலை முன்னறிவிப்பு',
    today: 'இன்று',
    tomorrow: 'நாளை',
    error: 'ஒரு பிழை ஏற்பட்டது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    errorApi: 'சேவையகத்திலிருந்து பதில் பெற முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    errorApiConnection: 'இணைப்புப் பிழை: {url} இல் உள்ள சேவையகத்துடன் இணைக்க முடியவில்லை. பின்தளம் இயங்குகிறதா என்பதையும் இந்தப் பக்கத்திலிருந்து வரும் கோரிக்கைகளை அனுமதிக்கிறதா என்பதையும் உறுதிப்படுத்தவும் (CORS).',
    agroChat: 'அக்ரோசாட்',
    chatPlaceholder: 'இந்த நோயறிதல் பற்றி எதையும் கேளுங்கள்...',
    chatError: 'மன்னிக்கவும், என்னால் பதிலளிக்க முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    noCropDetected: 'பயிர் எதுவும் கண்டறியப்படவில்லை',
    healthyCrop: 'ஆரோக்கியமான பயிர்',
    retranslating: 'மொழியைப் புதுப்பிக்கிறது...',
    detectAnother: 'மற்றொன்றைக் கண்டறியவும்',
    summary: 'சுருக்கம்',
    causes: 'சாத்தியமான காரணங்கள்',
    medicines: 'பரிந்துரைக்கப்பட்ட மருந்துகள்',
    precautions: 'முன்னெச்சரிக்கைகள்',
    disclaimer: 'பொறுப்புத் துறப்பு',
    dosage: 'மருந்தளவு/பயன்பாடு',
    notes: 'குறிப்புகள்',
    chatGreeting: 'உங்கள் பயிரில் "{diseaseName}" இருக்கலாம் என்று பார்க்கிறேன். இதில் நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    errorNoCamera: 'கேமரா எதுவும் இல்லை. தயவுசெய்து ஒரு கேமராவை இணைத்து மீண்டும் முயற்சிக்கவும்.',
    errorCameraPermission: 'கேமரா அணுகல் மறுக்கப்பட்டது. உங்கள் உலாவி அமைப்புகளில் கேமரா அனுமதியை அனுமதிக்கவும்.',
    errorCameraGeneric: 'கேமராவை அணுக முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    weatherLoading: 'வானிலை ஏற்றப்படுகிறது...',
    weatherErrorLocation: 'உங்கள் இருப்பிடத்தைப் பெற முடியவில்லை. வானிலையைப் பார்க்க இருப்பிட அணுகலை அனுமதிக்கவும்.',
    weatherErrorPermissionDenied: 'இருப்பிட அணுகல் மறுக்கப்பட்டது. வானிலையைப் பார்க்க உங்கள் உலாவி அமைப்புகளில் அதை இயக்கவும்.',
    weatherErrorPositionUnavailable: 'இந்த நேரத்தில் உங்கள் இருப்பிடத்தை தீர்மானிக்க முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    weatherErrorTimeout: 'இருப்பிடத்திற்கான கோரிக்கை நேரம் முடிந்தது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    weatherErrorApi: 'வானிலை தரவைப் பெற முடியவில்லை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
    weatherErrorNoKey: 'வானிலை சேவை கட்டமைக்கப்படவில்லை. உங்கள் OpenWeather API விசையைச் சேர்க்கவும்.',
    noValidLeafDetected: 'சரியான செடியின் இலை கண்டறியப்படவில்லை. தயவுசெய்து ஒரு தெளிவான செடி இலை படத்தை பதிவேற்றவும்.',
    tryAgain: 'மீண்டும் முயற்சி செய்',
    tryAnother: 'மற்றொன்றை முயற்சி செய்',
  },
};


export const LANGUAGES: { code: Language, name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'es', name: 'Español' },
  { code: 'ta', name: 'தமிழ்' },
];